project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Econ 106"
  favicon: "plot/econ106-logo.png"
  
  repo-url: https://econ106-com-prog.github.io/econ106-site/
  site-url: https://github.com/econ106-com-prog/econ106-site
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/econ106-logo.png"
    contents:
      - href: "index.qmd"
        text: "**Home**"
      - section: "**Topics**"
        contents:
          - href: "module-1-intro-r-programming.qmd"
            text: "Module 1: Introduction to R programming"
          - href: ""
            text: "Module 2: Data management and transformation with Tidyverse"
          - href: ""
            text: "Module 3: Data visualization with ggplot2"
          - href: ""
            text: "Module 4: Exploratory data analysis (EDA)"
          - href: ""
            text: "Module 5: Data analysis report with Quarto"
          - href: ""
            text: "Module 6: Version control with Git and Github"
          - href: ""
            text: "Module 7: Creating a Quarto website"

      - section: "**Laboratory exercises**"
        contents:
          - href: "quizzes.qmd"
            text: "Quizzes"
          - href: "module-1-exercise-1.qmd"
            text: "Exercise 1: Introduction to R programming"

      - section: "**Class records**"
        contents:
          - href: "class-record.qmd"
            text: "Grades"
          - href: "quizzes.qmd"
            text: "Quizzes"

         

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual